version: '3'
networks:
    monitoring-net:
        driver: bridge
services:
    prometheus:
        image: prom/prometheus:latest
        container_name: monitoring_prometheus
        restart: unless-stopped
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./data/prometheus:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        expose:
            - 9090
        ports:
            - '9090:9090'
        networks: 
            - monitoring-net
        links: 
            - synthetic-airpa
    synthetic-airpa:
        image: prometheus-synthetic-airpa
        container_name: monitoring_synthetic_airpa
        restart: unless-stopped
        expose:
            - 9901
        ports:
            - '9901:9901'
        networks: 
            - monitoring-net
    grafana:
        image: grafana/grafana:latest
        container_name: monitoring_grafana
        restart: unless-stopped
        links:
            - prometheus:prometheus
        volumes:
            - ./data/grafana:/var/lib/grafana
        expose:
            - 3000
        ports:
            - 3000:3000
